import line_environment as lenv

env = lenv.lineEnvironment()
print(env.reset())
print()
print()
print(0.1)
print(env.step(0.1))
print()
print(-0.2)
print(env.step(-0.2))
print()
print(0.25)
print(env.step(0.25))
print()
print(-0.25)
print(env.step(-0.25))
print()
print(0.1)
print(env.step(0.1))
print()
print(0.1)
print(env.step(0.1))

